// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTrIoa5mweHiONqnz-shkwKnSq67GkA3o',
    appId: '1:986496188100:web:43ea472c9322bb43e6d391',
    messagingSenderId: '986496188100',
    projectId: 'quiet-app-afa49',
    authDomain: 'quiet-app-afa49.firebaseapp.com',
    storageBucket: 'quiet-app-afa49.firebasestorage.app',
    measurementId: 'G-1KWTFRMCEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDScHBgxWm9h_kMOm-wvRgAXND77U8MMMM',
    appId: '1:986496188100:android:909a0f9b448b09dfe6d391',
    messagingSenderId: '986496188100',
    projectId: 'quiet-app-afa49',
    storageBucket: 'quiet-app-afa49.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLpbRw3Wp0rKg0w56C4f35t7Uaq63vfI0',
    appId: '1:986496188100:ios:d5407a0e4306f447e6d391',
    messagingSenderId: '986496188100',
    projectId: 'quiet-app-afa49',
    storageBucket: 'quiet-app-afa49.firebasestorage.app',
    iosClientId: '986496188100-1t485ljdndm8fnvbenm4lrl4mj1e86h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQuiet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLpbRw3Wp0rKg0w56C4f35t7Uaq63vfI0',
    appId: '1:986496188100:ios:d5407a0e4306f447e6d391',
    messagingSenderId: '986496188100',
    projectId: 'quiet-app-afa49',
    storageBucket: 'quiet-app-afa49.firebasestorage.app',
    iosClientId: '986496188100-1t485ljdndm8fnvbenm4lrl4mj1e86h6.apps.googleusercontent.com',
    iosBundleId: 'com.example.appQuiet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnqqVC1ik2rKny6i3IdGb8X_9KxFDlths',
    appId: '1:986496188100:web:880e9d2536d261e6e6d391',
    messagingSenderId: '986496188100',
    projectId: 'quiet-app-afa49',
    authDomain: 'quiet-app-afa49.firebaseapp.com',
    storageBucket: 'quiet-app-afa49.firebasestorage.app',
    measurementId: 'G-P976HD8MS6',
  );
}
